variables:
    GIT_SSL_NO_VERIFY: "true"
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - docker info

stages:
    - build

code_quality:
    stage: build
    image: python:latest
    before_script:
        - python -V
    script:
        - pip install flake8
        - flake8
    tags:
        - docker

build_image:
    stage: build
    before_script:
        - pip install docker-compose
    script:
        - docker-compose build
    tags:
        - shell
