version: "3"

services:
    infer:
        build: face-recognition-inference
    front:
        build: simple-frontend
        depends_on:
            - infer
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - front
        ports:
            - "8000:80"
